default_language_version:
  python: python3
  
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg      
  
repos:
# Various Built-in Checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch
      description: only commit to allowed branches
      args: ['--pattern', '^(?!(((feature|hotfix|bugfix))\/(IKM|AR|IAT|IC|IKMC|IKDT|IKMD|IIA|IKMW|IKMM|TE)-\d+(-[0-9A-Za-z\-]*)*)|main|prod|master|dev).*$']
      stages: [pre-commit]

# Jira Ticket Link Prepender     
- repo: https://github.com/jlgrock/prepend-jira-ticket-number
  rev: v0.2.0
  hooks:
    - id: prepend-jira-ticket-number
      description: Appends ticket number and link below commit message based on the branch name
      stages: [prepare-commit-msg]


